### PR TITLE
Proposition of better documentation

### PR DESCRIPTION
**Pull request by heimsi**
Hey Jeff,
This is a bit of a misuse of a pull request, but I couldn't find another way to contact you. I'm a Masters Student at ETH Zurich, and I would like to use the elas_ros package for my research. But I am not able to build the package.  Here would be the deal: you tell me how to build the package, and I document it in the readme-file, such that for the future other people can use this (very interesting) package more easily. :) What do you think? my email: heimsi@ethz.ch

### CODE REVIEW

**Comment by jzheng84** [comment]
I am having trouble building the package as well. @heimsi were you able to document the instructions?

**Comment by heimsi** [comment]
Hey jzheng84,
I was finally able to build the package. Here is what you have to do ( I can not say it's the easiest way, but for me it worked):
1. download the repository to your catkin src
2. move the three subfolder of elas, elas_ros and libelas into src
3. In libelas/CMakeLists.txt change all the arguments of command `cs_add_library(...)` from `libelas/src/[...].cpp` to `src/[...].cpp`  
4. get  [catkin_simple](https://github.com/catkin/catkin_simple)  and build it
5. build elas, which is a metapackage, which then builds libelas and elas_ros.

I tested the software, and I was a bit disillusioned. The disparity image calculation, which is the main focus of this software, seems to be quite good. But packed on top is a rather simple point cloud merging algorithm. The algorithm lacks noise filtering capabilities, such that if you input a higher number of pictures the point cloud gets very very big and very noisy, and frankly, unusable. If you are interested in live mapping based on stereo images, I think you should for example better look at [RTAB](http://wiki.ros.org/rtabmap).

Best regards,

Silvan

**Comment by jzheng84** [comment]
Silvan,

Thank you, I appreciate it.

Justin

**Comment by jeffdelmerico** [comment]
Hi all,

Apologies that this response is coming two years too late.  I had forked this repo from the original developers and made some modifications to suit my own needs, but I was never the maintainer.  However, in the years since I last used this code, apparently the original repo has disappeared, so now it looks like this is the primary source for libelas, and I am by default the maintainer.  Sorry I missed your original PR, but I will try to clean up the repo a bit, including the documentation.

-Jeff

**Comment by Gaochao-hit** [comment]
> Hi all,
> 
> Apologies that this response is coming two years too late. I had forked this repo from the original developers and made some modifications to suit my own needs, but I was never the maintainer. However, in the years since I last used this code, apparently the original repo has disappeared, so now it looks like this is the primary source for libelas, and I am by default the maintainer. Sorry I missed your original PR, but I will try to clean up the repo a bit, including the documentation.
> 
> -Jeff

hello, I build the project successfully. but the frequency of publishing depth is really slow and i can't figure the reason. although I played the bag in a low rate.

**Comment by jeffdelmerico** [comment]
I've re-enabled issues for this repo.  Please file this as a new issue and I can try to help.  Please include much more information about the problem (e.g. what executable are you running, what is the size and rate of the input, what rate is the output, etc.)

**Pull request closed without merging**
