### PR TITLE
Install commands 

### PR DESCRIPTION
**Pull request by marcin-ochman**
In CMake scripts there's lack of install commands required for installation process or creating deb packages.

### CODE REVIEW

**Comment by jeffdelmerico** [comment]
Thanks for implementing this.  You should add a note in the build instructions that the catkin workspace should be set to have "merged" devel space rather than "linked".  I received some warning about failed symlinks when using the "linked" devel space, but the build succeeded.  Otherwise, this looks good to me.

**Comment by marcin-ochman** [comment]
Could you provide logs and used commands? I've tested both - merged and linked devel space. There's no warnings related to symlinks on my two PCs (Ubuntu and Manjaro).

**Comment by jeffdelmerico** [comment]
Here is my output for the linked devel space:
```
jeff@DESKTOP-MIS3H5J:~$ mkdir -p cyphy_ws/src
jeff@DESKTOP-MIS3H5J:~$ cd cyphy_ws/
jeff@DESKTOP-MIS3H5J:~/cyphy_ws$ catkin init
Initializing catkin workspace in `/home/jeff/cyphy_ws`.
------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/jeff/catkin_ws/devel:/opt/ros/melodic
Workspace:                   /home/jeff/cyphy_ws
------------------------------------------------------------------------
Source Space:       [exists] /home/jeff/cyphy_ws/src
Log Space:         [missing] /home/jeff/cyphy_ws/logs
Build Space:       [missing] /home/jeff/cyphy_ws/build
Devel Space:       [missing] /home/jeff/cyphy_ws/devel
Install Space:      [unused] /home/jeff/cyphy_ws/install
DESTDIR:            [unused] None
------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------------
jeff@DESKTOP-MIS3H5J:~/cyphy_ws$ cd src/
jeff@DESKTOP-MIS3H5J:~/cyphy_ws/src$ git clone https://github.com/marcin-ochman/cyphy-elas-ros.git
Cloning into 'cyphy-elas-ros'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 181 (delta 0), reused 3 (delta 0), pack-reused 175
Receiving objects: 100% (181/181), 154.27 KiB | 810.00 KiB/s, done.
Resolving deltas: 100% (71/71), done.
jeff@DESKTOP-MIS3H5J:~/cyphy_ws/src$ catkin build
------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/jeff/catkin_ws/devel:/opt/ros/melodic
Workspace:                   /home/jeff/cyphy_ws
------------------------------------------------------------------------
Source Space:       [exists] /home/jeff/cyphy_ws/src
Log Space:         [missing] /home/jeff/cyphy_ws/logs
Build Space:        [exists] /home/jeff/cyphy_ws/build
Devel Space:        [exists] /home/jeff/cyphy_ws/devel
Install Space:      [unused] /home/jeff/cyphy_ws/install
DESTDIR:            [unused] None
------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------------------------
[build] Found '2' packages in 0.0 seconds.
[build] Updating package table.
Starting  >>> catkin_tools_prebuild
Finished  <<< catkin_tools_prebuild                [ 19.5 seconds ]
Starting  >>> libelas
___________________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << libelas:make /home/jeff/cyphy_ws/logs/libelas/build.make.000.log
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp: In member function ‘void Elas::computeDisparity(std::vector<Elas::support_pt>, std::vector<Elas::triangle>, int32_t*, int32_t*, uint8_t*, uint8_t*, bool, float*)’:
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp:833:37: warning: narrowing conversion of ‘p_support.std::vector<Elas::support_pt>::operator[](((std::vector<Elas::support_pt>::size_type)c1)).Elas::support_pt::v’ from ‘int32_t {aka int}’ to ‘float’ inside { } [-Wnarrowing]
     float tri_v[3] = {p_support[c1].v,p_support[c2].v,p_support[c3].v};
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp:833:53: warning: narrowing conversion of ‘p_support.std::vector<Elas::support_pt>::operator[](((std::vector<Elas::support_pt>::size_type)c2)).Elas::support_pt::v’ from ‘int32_t {aka int}’ to ‘float’ inside { } [-Wnarrowing]
     float tri_v[3] = {p_support[c1].v,p_support[c2].v,p_support[c3].v};
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp:833:69: warning: narrowing conversion of ‘p_support.std::vector<Elas::support_pt>::operator[](((std::vector<Elas::support_pt>::size_type)c3)).Elas::support_pt::v’ from ‘int32_t {aka int}’ to ‘float’ inside { } [-Wnarrowing]
     float tri_v[3] = {p_support[c1].v,p_support[c2].v,p_support[c3].v};
cd /home/jeff/cyphy_ws/build/libelas; catkin build --get-env libelas | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...................................................................................................................................................................................................................
___________________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << libelas:symlink /home/jeff/cyphy_ws/logs/libelas/build.symlink.000.log
Warning: Cannot symlink from /home/jeff/cyphy_ws/devel/.private/libelas/local_setup.sh to existing file /home/jeff/cyphy_ws/devel/./local_setup.sh
Warning: Source hash: 54fb08cd63893874aacac2a65e54de84
Warning: Dest hash: cebec4eec3a6a66810fcee101734d70d
...................................................................................................................................................................................................................
Finished  <<< libelas                              [ 16.9 seconds ]
Starting  >>> elas_ros
___________________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << elas_ros:make /home/jeff/cyphy_ws/logs/elas_ros/build.make.000.log
/home/jeff/cyphy_ws/src/cyphy-elas-ros/elas_ros/src/elas.cpp: In member function ‘void Elas_Proc::process(const ImageConstPtr&, const ImageConstPtr&, const CameraInfoConstPtr&, const CameraInfoConstPtr&)’:
/home/jeff/cyphy_ws/src/cyphy-elas-ros/elas_ros/src/elas.cpp:331:43: warning: narrowing conversion of ‘(sensor_msgs::Image_<std::allocator<void> >::_width_type)(& l_image_msg)->boost::shared_ptr<const sensor_msgs::Image_<std::allocator<void> > >::operator->()->sensor_msgs::Image_<std::allocator<void> >::width’ from ‘sensor_msgs::Image_<std::allocator<void> >::_width_type {aka unsigned int}’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
     const int32_t dims[3] = {l_image_msg->width, l_image_msg->height, l_step};
                              ~~~~~~~~~~~~~^~~~~
/home/jeff/cyphy_ws/src/cyphy-elas-ros/elas_ros/src/elas.cpp:331:63: warning: narrowing conversion of ‘(sensor_msgs::Image_<std::allocator<void> >::_height_type)(& l_image_msg)->boost::shared_ptr<const sensor_msgs::Image_<std::allocator<void> > >::operator->()->sensor_msgs::Image_<std::allocator<void> >::height’ from ‘sensor_msgs::Image_<std::allocator<void> >::_height_type {aka unsigned int}’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
     const int32_t dims[3] = {l_image_msg->width, l_image_msg->height, l_step};
                                                  ~~~~~~~~~~~~~^~~~~~
cd /home/jeff/cyphy_ws/build/elas_ros; catkin build --get-env elas_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...................................................................................................................................................................................................................
___________________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << elas_ros:symlink /home/jeff/cyphy_ws/logs/elas_ros/build.symlink.000.log
Warning: Cannot symlink from /home/jeff/cyphy_ws/devel/.private/elas_ros/local_setup.sh to existing file /home/jeff/cyphy_ws/devel/./local_setup.sh
Warning: Source hash: 2bcd91a573384e7415dac9de520f0dc7
Warning: Dest hash: cebec4eec3a6a66810fcee101734d70d
...................................................................................................................................................................................................................
Finished  <<< elas_ros                             [ 52.7 seconds ]
[build] Summary: All 3 packages succeeded!
[build]   Ignored:   None.
[build]   Warnings:  2 packages succeeded with warnings.
[build]   Abandoned: None.
[build]   Failed:    None.
[build] Runtime: 1 minute and 29.6 seconds total.
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```

And for merged:
```
jeff@DESKTOP-MIS3H5J:~/cyphy_ws/src$ catkin config --merge-devel
------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/jeff/catkin_ws/devel:/opt/ros/melodic
Workspace:                   /home/jeff/cyphy_ws
------------------------------------------------------------------------
Source Space:       [exists] /home/jeff/cyphy_ws/src
Log Space:          [exists] /home/jeff/cyphy_ws/logs
Build Space:        [exists] /home/jeff/cyphy_ws/build
Devel Space:        [exists] /home/jeff/cyphy_ws/devel
Install Space:      [unused] /home/jeff/cyphy_ws/install
DESTDIR:            [unused] None
------------------------------------------------------------------------
Devel Space Layout:          merged
Install Space Layout:        None
------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------------
jeff@DESKTOP-MIS3H5J:~/cyphy_ws/src$ catkin clean

[clean] Warning: This will completely remove the following directories. (Use `--yes` to skip this check)
[clean] Log Space:     /home/jeff/cyphy_ws/logs
[clean] Build Space:   /home/jeff/cyphy_ws/build
[clean] Devel Space:   /home/jeff/cyphy_ws/devel

[clean] Are you sure you want to completely remove the directories listed above? [yN]: y
[clean] Removing develspace: /home/jeff/cyphy_ws/devel
[clean] Removing buildspace: /home/jeff/cyphy_ws/build
[clean] Removing log space: /home/jeff/cyphy_ws/logs
jeff@DESKTOP-MIS3H5J:~/cyphy_ws/src$ catkin build
------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/jeff/catkin_ws/devel:/opt/ros/melodic
Workspace:                   /home/jeff/cyphy_ws
------------------------------------------------------------------------
Source Space:       [exists] /home/jeff/cyphy_ws/src
Log Space:         [missing] /home/jeff/cyphy_ws/logs
Build Space:        [exists] /home/jeff/cyphy_ws/build
Devel Space:        [exists] /home/jeff/cyphy_ws/devel
Install Space:      [unused] /home/jeff/cyphy_ws/install
DESTDIR:            [unused] None
------------------------------------------------------------------------
Devel Space Layout:          merged
Install Space Layout:        None
------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------------------------
[build] Found '2' packages in 0.0 seconds.
[build] Updating package table.
Starting  >>> libelas
___________________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << libelas:make /home/jeff/cyphy_ws/logs/libelas/build.make.000.log
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp: In member function ‘void Elas::computeDisparity(std::vector<Elas::support_pt>, std::vector<Elas::triangle>, int32_t*, int32_t*, uint8_t*, uint8_t*, bool, float*)’:
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp:833:37: warning: narrowing conversion of ‘p_support.std::vector<Elas::support_pt>::operator[](((std::vector<Elas::support_pt>::size_type)c1)).Elas::support_pt::v’ from ‘int32_t {aka int}’ to ‘float’ inside { } [-Wnarrowing]
     float tri_v[3] = {p_support[c1].v,p_support[c2].v,p_support[c3].v};
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp:833:53: warning: narrowing conversion of ‘p_support.std::vector<Elas::support_pt>::operator[](((std::vector<Elas::support_pt>::size_type)c2)).Elas::support_pt::v’ from ‘int32_t {aka int}’ to ‘float’ inside { } [-Wnarrowing]
     float tri_v[3] = {p_support[c1].v,p_support[c2].v,p_support[c3].v};
/home/jeff/cyphy_ws/src/cyphy-elas-ros/libelas/src/elas.cpp:833:69: warning: narrowing conversion of ‘p_support.std::vector<Elas::support_pt>::operator[](((std::vector<Elas::support_pt>::size_type)c3)).Elas::support_pt::v’ from ‘int32_t {aka int}’ to ‘float’ inside { } [-Wnarrowing]
     float tri_v[3] = {p_support[c1].v,p_support[c2].v,p_support[c3].v};
cd /home/jeff/cyphy_ws/build/libelas; catkin build --get-env libelas | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...................................................................................................................................................................................................................
Finished  <<< libelas                 [ 20.4 seconds ]
Starting  >>> elas_ros
___________________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << elas_ros:make /home/jeff/cyphy_ws/logs/elas_ros/build.make.000.log
/home/jeff/cyphy_ws/src/cyphy-elas-ros/elas_ros/src/elas.cpp: In member function ‘void Elas_Proc::process(const ImageConstPtr&, const ImageConstPtr&, const CameraInfoConstPtr&, const CameraInfoConstPtr&)’:
/home/jeff/cyphy_ws/src/cyphy-elas-ros/elas_ros/src/elas.cpp:331:43: warning: narrowing conversion of ‘(sensor_msgs::Image_<std::allocator<void> >::_width_type)(& l_image_msg)->boost::shared_ptr<const sensor_msgs::Image_<std::allocator<void> > >::operator->()->sensor_msgs::Image_<std::allocator<void> >::width’ from ‘sensor_msgs::Image_<std::allocator<void> >::_width_type {aka unsigned int}’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
     const int32_t dims[3] = {l_image_msg->width, l_image_msg->height, l_step};
                              ~~~~~~~~~~~~~^~~~~
/home/jeff/cyphy_ws/src/cyphy-elas-ros/elas_ros/src/elas.cpp:331:63: warning: narrowing conversion of ‘(sensor_msgs::Image_<std::allocator<void> >::_height_type)(& l_image_msg)->boost::shared_ptr<const sensor_msgs::Image_<std::allocator<void> > >::operator->()->sensor_msgs::Image_<std::allocator<void> >::height’ from ‘sensor_msgs::Image_<std::allocator<void> >::_height_type {aka unsigned int}’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
     const int32_t dims[3] = {l_image_msg->width, l_image_msg->height, l_step};
                                                  ~~~~~~~~~~~~~^~~~~~
cd /home/jeff/cyphy_ws/build/elas_ros; catkin build --get-env elas_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...................................................................................................................................................................................................................
Finished  <<< elas_ros                [ 50.6 seconds ]
[build] Summary: All 2 packages succeeded!
[build]   Ignored:   None.
[build]   Warnings:  2 packages succeeded with warnings.
[build]   Abandoned: None.
[build]   Failed:    None.
[build] Runtime: 1 minute and 11.4 seconds total.
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```

This is on Ubuntu 18.04 within Windows Subsystem for Linux (WSL).  I have not had the chance to try this on my native Ubuntu install, but I assume now that the warnings are an artifact of WSL and not anything to do with the install commands that you added.  

While it may still be worthwhile to add a note about this error for other WSL users, it's not clear if this would actually affect any functionality, because it's just the local_setup.sh files and none of the executables, headers, etc.

I'm fine with merging this PR.

**Comment by marcin-ochman** [comment]
You closed PR, but changes were not merged. Was it intended?

**Comment by jeffdelmerico** [comment]
Sorry, I only intended to comment, not close it.  Merging now.

**Pull request merged**
